config/routes.rb
Rails.application.routes.draw do
  resources :universal_channels
  resources :global_channels
  resources :local_channels
  resources :nodes

end

app/models/_node.rb
=begin
#t.integer :l_channel              #local channel (relationships, family, etc)
#t.integer :g_channel              #global channel (laws, traditions, local news)
#t.integer :e_channel             #ego channel (stores all broadcasts from a given node)?  i.e. personal truths
=                                 #universal channel ("universal truths," like math and the like, all nodes are subscribed)
t.integer :l_weight               #width of the pipe through which the local channel is piped
t.integer :g_weight               #" global channel
t.integer :u_weight               #" universal channel
#t.integer :g_efficiency           #number of ticks required to generate a share for global
#t.integer :l_efficiency           #number of ticks required to generate a share for local
#t.integer :u_efficiency           #number of ticks required to generate a share for universe
t.string :queue                    #stores the last response generated for broadcast
=end

require "moby"

class Node < ActiveRecord::Base

#============================================================================#

  def work()
    @state = rand(2)  #0 = off/sleeping
                      #1 = receiving
                      #2 = broadcasting

    @broadcast_channel = rand(2) #0 = local
                                 #1 = global
                                 #2 = universe

    case @state
    
    when 0
      return 0
   
    when 1
      @i_packet = []                                                      #received packets
      @l_packet = LocalChannel.limit(self.l_weight).order("RAND()")       #TODO turn this into a class method like .generate_packet
      @g_packet = GlobalChannel.limit(self.g_weight).order("RAND()")      #"
      @u_packet = UniversalChannel.limit(self.u_weight).order("RAND()")   #"

      @l_packet.each do |p|
        @i_packet.push(p.message)
      end
      
      @g_packet.each do |p|
        @i_packet.push(p.message)
      end

      @u_packet.each do |p|
        @i_packet.push(p.message)
      end

      self.koanize(@i_packet)
      
    when 2
      self.broadcast()
      
    else
      return 0
      
    end
    
  end

#============================================================================#  

  def koanize(ary)
    response = []

    ary = ary.split(" ")

    ary.each do |w| 
      c = $thesaurus.synonyms(w).sample()

      if c.nil?
        response << w
      else
        response << c
      end
    end

    response.shuffle!
    self.queue = (response.sample().join(" "))
    self.save!

    end

  end

#============================================================================#

  def broadcast()
    if self.queue?
      case @broadcast_channel
      when 0
        LocalChannel.new(self.queue)
        
      when 1
        GlobalChannel.new(self.queue)
        
      when 2
        UniversalChannel.new(self.queue)
        
      else
        return 0
        
      end

    else
      return 0
      
    end
  end

end

app/models/node.rb
=begin
#t.integer :l_channel              #local channel (relationships, family, etc)
#t.integer :g_channel              #global channel (laws, traditions, local news)
#t.integer :e_channel             #ego channel (stores all broadcasts from a given node)?  i.e. personal truths
=                                 #universal channel ("universal truths," like math and the like, all nodes are subscribed)
t.integer :l_weight               #width of the pipe through which the local channel is piped
t.integer :g_weight               #" global channel
t.integer :u_weight               #" universal channel
#t.integer :g_efficiency           #number of ticks required to generate a share for global
#t.integer :l_efficiency           #number of ticks required to generate a share for local
#t.integer :u_efficiency           #number of ticks required to generate a share for universe
t.string :queue                    #stores the last response generated for broadcast
=end

require "moby"

class Node < ActiveRecord::Base

#============================================================================#

  def work()
    @state = rand(3)  #0 = off/sleeping
                      #1 = receiving
                      #2 = broadcasting

    puts @state
    
    @broadcast_channel = rand(3) #0 = local
                                 #1 = global
                                 #2 = universe

    case @state
    
    when 0
      return 0
   
    when 1
      @i_packet = ""                                                       #received packets
      @l_packet = LocalChannel.limit(self.l_weight).order("Random()")      #TODO turn this into a class method like .generate_packet
      @g_packet = GlobalChannel.limit(self.g_weight).order("Random()")     #"
      @u_packet = UniversalChannel.limit(self.u_weight).order("Random()")  #"

      @l_packet.each do |p|
        @i_packet = @i_packet + " " + p.message
      end
      
      @g_packet.each do |p|
        @i_packet = @i_packet + " " + p.message
      end

      @u_packet.each do |p|
        @i_packet = @i_packet + " " + p.message
      end

      self.koanize(@i_packet)
      
    when 2
      self.broadcast()
      
    else
      return 0
      
    end
    
  end

#============================================================================#  

  def koanize(str)
    tokens = str.split(" ")
    response = []

    tokens.each do |w| 
      c = $thesaurus.synonyms(w).sample()

      if c.nil?
        response << w
      else
        response << c
      end
    end

    response.shuffle!
    self.queue = (response.join(" "))
    self.save!

  end

#============================================================================#

  def broadcast()
    if self.queue?
      case @broadcast_channel
      when 0
        puts "Local: " + self.queue
        x = LocalChannel.new(:message => self.queue)
        x.save!
        
      when 1
        puts "Global: " + self.queue
        x = GlobalChannel.new(:message => self.queue)
        x.save!
        
      when 2
        puts "Universal: " + self.queue
        x = UniversalChannel.new(:message => self.queue)
        x.save!
      else
        return 0
        
      end

    else
      return 0
      
    end
  end

end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:l_weight, :g_weight, :u_weight, :queue)
    end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :l_weight %><br>
    <%= f.number_field :l_weight %>
  </div>
  <div class="field">
    <%= f.label :g_weight %><br>
    <%= f.number_field :g_weight %>
  </div>
  <div class="field">
    <%= f.label :u_weight %><br>
    <%= f.number_field :u_weight %>
  </div>
  <div class="field">
    <%= f.label :queue %><br>
    <%= f.text_field :queue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing Node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Nodes</h1>

<table>
  <thead>
    <tr>
      <th>L weight</th>
      <th>G weight</th>
      <th>U weight</th>
      <th>Queue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= node.l_weight %></td>
        <td><%= node.g_weight %></td>
        <td><%= node.u_weight %></td>
        <td><%= node.queue %></td>
        <td><%= link_to 'Show', node %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New Node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>L weight:</strong>
  <%= @node.l_weight %>
</p>

<p>
  <strong>G weight:</strong>
  <%= @node.g_weight %>
</p>

<p>
  <strong>U weight:</strong>
  <%= @node.u_weight %>
</p>

<p>
  <strong>Queue:</strong>
  <%= @node.queue %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>