config/routes.rb
Rails.application.routes.draw do
  resources :universal_channels
  resources :global_channels
  resources :local_channels
  resources :nodes

end

app/models/global_channel.rb
class GlobalChannel < ActiveRecord::Base
end

app/controllers/global_channels_controller.rb
class GlobalChannelsController < ApplicationController
  before_action :set_global_channel, only: [:show, :edit, :update, :destroy]

  # GET /global_channels
  # GET /global_channels.json
  def index
    @global_channels = GlobalChannel.all
  end

  # GET /global_channels/1
  # GET /global_channels/1.json
  def show
  end

  # GET /global_channels/new
  def new
    @global_channel = GlobalChannel.new
  end

  # GET /global_channels/1/edit
  def edit
  end

  # POST /global_channels
  # POST /global_channels.json
  def create
    @global_channel = GlobalChannel.new(global_channel_params)

    respond_to do |format|
      if @global_channel.save
        format.html { redirect_to @global_channel, notice: 'Global channel was successfully created.' }
        format.json { render :show, status: :created, location: @global_channel }
      else
        format.html { render :new }
        format.json { render json: @global_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /global_channels/1
  # PATCH/PUT /global_channels/1.json
  def update
    respond_to do |format|
      if @global_channel.update(global_channel_params)
        format.html { redirect_to @global_channel, notice: 'Global channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @global_channel }
      else
        format.html { render :edit }
        format.json { render json: @global_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /global_channels/1
  # DELETE /global_channels/1.json
  def destroy
    @global_channel.destroy
    respond_to do |format|
      format.html { redirect_to global_channels_url, notice: 'Global channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_global_channel
      @global_channel = GlobalChannel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def global_channel_params
      params.require(:global_channel).permit(:message)
    end
end

app/helpers/global_channels_helper.rb
module GlobalChannelsHelper
end

app/views/global_channels/_form.html.erb
<%= form_for(@global_channel) do |f| %>
  <% if @global_channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@global_channel.errors.count, "error") %> prohibited this global_channel from being saved:</h2>

      <ul>
      <% @global_channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/global_channels/edit.html.erb
<h1>Editing Global Channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @global_channel %> |
<%= link_to 'Back', global_channels_path %>

app/views/global_channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Global Channels</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @global_channels.each do |global_channel| %>
      <tr>
        <td><%= global_channel.message %></td>
        <td><%= link_to 'Show', global_channel %></td>
        <td><%= link_to 'Edit', edit_global_channel_path(global_channel) %></td>
        <td><%= link_to 'Destroy', global_channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Global channel', new_global_channel_path %>

app/views/global_channels/new.html.erb
<h1>New Global Channel</h1>

<%= render 'form' %>

<%= link_to 'Back', global_channels_path %>

app/views/global_channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @global_channel.message %>
</p>

<%= link_to 'Edit', edit_global_channel_path(@global_channel) %> |
<%= link_to 'Back', global_channels_path %>