config/routes.rb
Rails.application.routes.draw do
  resources :universal_channels
  resources :global_channels
  resources :local_channels
  resources :nodes

end

app/models/local_channel.rb
class LocalChannel < ActiveRecord::Base
end

app/controllers/local_channels_controller.rb
class LocalChannelsController < ApplicationController
  before_action :set_local_channel, only: [:show, :edit, :update, :destroy]

  # GET /local_channels
  # GET /local_channels.json
  def index
    @local_channels = LocalChannel.all
  end

  # GET /local_channels/1
  # GET /local_channels/1.json
  def show
  end

  # GET /local_channels/new
  def new
    @local_channel = LocalChannel.new
  end

  # GET /local_channels/1/edit
  def edit
  end

  # POST /local_channels
  # POST /local_channels.json
  def create
    @local_channel = LocalChannel.new(local_channel_params)

    respond_to do |format|
      if @local_channel.save
        format.html { redirect_to @local_channel, notice: 'Local channel was successfully created.' }
        format.json { render :show, status: :created, location: @local_channel }
      else
        format.html { render :new }
        format.json { render json: @local_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /local_channels/1
  # PATCH/PUT /local_channels/1.json
  def update
    respond_to do |format|
      if @local_channel.update(local_channel_params)
        format.html { redirect_to @local_channel, notice: 'Local channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @local_channel }
      else
        format.html { render :edit }
        format.json { render json: @local_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /local_channels/1
  # DELETE /local_channels/1.json
  def destroy
    @local_channel.destroy
    respond_to do |format|
      format.html { redirect_to local_channels_url, notice: 'Local channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local_channel
      @local_channel = LocalChannel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_channel_params
      params.require(:local_channel).permit(:message)
    end
end

app/helpers/local_channels_helper.rb
module LocalChannelsHelper
end

app/views/local_channels/_form.html.erb
<%= form_for(@local_channel) do |f| %>
  <% if @local_channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@local_channel.errors.count, "error") %> prohibited this local_channel from being saved:</h2>

      <ul>
      <% @local_channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/local_channels/edit.html.erb
<h1>Editing Local Channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @local_channel %> |
<%= link_to 'Back', local_channels_path %>

app/views/local_channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Local Channels</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @local_channels.each do |local_channel| %>
      <tr>
        <td><%= local_channel.message %></td>
        <td><%= link_to 'Show', local_channel %></td>
        <td><%= link_to 'Edit', edit_local_channel_path(local_channel) %></td>
        <td><%= link_to 'Destroy', local_channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Local channel', new_local_channel_path %>

app/views/local_channels/new.html.erb
<h1>New Local Channel</h1>

<%= render 'form' %>

<%= link_to 'Back', local_channels_path %>

app/views/local_channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @local_channel.message %>
</p>

<%= link_to 'Edit', edit_local_channel_path(@local_channel) %> |
<%= link_to 'Back', local_channels_path %>