config/routes.rb
Rails.application.routes.draw do
  resources :universal_channels
  resources :global_channels
  resources :local_channels
  resources :nodes

end

app/models/universal_channel.rb
class UniversalChannel < ActiveRecord::Base
end

app/controllers/universal_channels_controller.rb
class UniversalChannelsController < ApplicationController
  before_action :set_universal_channel, only: [:show, :edit, :update, :destroy]

  # GET /universal_channels
  # GET /universal_channels.json
  def index
    @universal_channels = UniversalChannel.all
  end

  # GET /universal_channels/1
  # GET /universal_channels/1.json
  def show
  end

  # GET /universal_channels/new
  def new
    @universal_channel = UniversalChannel.new
  end

  # GET /universal_channels/1/edit
  def edit
  end

  # POST /universal_channels
  # POST /universal_channels.json
  def create
    @universal_channel = UniversalChannel.new(universal_channel_params)

    respond_to do |format|
      if @universal_channel.save
        format.html { redirect_to @universal_channel, notice: 'Universal channel was successfully created.' }
        format.json { render :show, status: :created, location: @universal_channel }
      else
        format.html { render :new }
        format.json { render json: @universal_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universal_channels/1
  # PATCH/PUT /universal_channels/1.json
  def update
    respond_to do |format|
      if @universal_channel.update(universal_channel_params)
        format.html { redirect_to @universal_channel, notice: 'Universal channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @universal_channel }
      else
        format.html { render :edit }
        format.json { render json: @universal_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universal_channels/1
  # DELETE /universal_channels/1.json
  def destroy
    @universal_channel.destroy
    respond_to do |format|
      format.html { redirect_to universal_channels_url, notice: 'Universal channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_universal_channel
      @universal_channel = UniversalChannel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def universal_channel_params
      params.require(:universal_channel).permit(:message)
    end
end

app/helpers/universal_channels_helper.rb
module UniversalChannelsHelper
end

app/views/universal_channels/_form.html.erb
<%= form_for(@universal_channel) do |f| %>
  <% if @universal_channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@universal_channel.errors.count, "error") %> prohibited this universal_channel from being saved:</h2>

      <ul>
      <% @universal_channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/universal_channels/edit.html.erb
<h1>Editing Universal Channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @universal_channel %> |
<%= link_to 'Back', universal_channels_path %>

app/views/universal_channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Universal Channels</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @universal_channels.each do |universal_channel| %>
      <tr>
        <td><%= universal_channel.message %></td>
        <td><%= link_to 'Show', universal_channel %></td>
        <td><%= link_to 'Edit', edit_universal_channel_path(universal_channel) %></td>
        <td><%= link_to 'Destroy', universal_channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Universal channel', new_universal_channel_path %>

app/views/universal_channels/new.html.erb
<h1>New Universal Channel</h1>

<%= render 'form' %>

<%= link_to 'Back', universal_channels_path %>

app/views/universal_channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @universal_channel.message %>
</p>

<%= link_to 'Edit', edit_universal_channel_path(@universal_channel) %> |
<%= link_to 'Back', universal_channels_path %>